### ISSUE TITLE
NPCScan repo gone

### ISSUE THREAD

**Issue by stevietv** [layday/github-wow-addon-catalogue#5]
NPCSCan repo needs removing.

**Comment by layday** [comment]
Thanks - I've been working on adding a command to prune deleted add-ons. The issue is that the GH search API results are not stable and if a repo is missing from the result set that doesn't necessarily mean that it's been deleted.  In the future, I'll be removing repos that haven't appeared for _x_ days after _y_ consecutive runs.

**Comment by layday** [comment]
Done in https://github.com/layday/github-wow-addon-catalogue/commit/9fabec5bb808932983a937e4f413d900693d73dc.

**Comment by layday** [comment]
Hey @torkus, I've added a new col `last_seen` with this change - just in case you need to change something on your end.

**Comment by torkus** [comment]
Much appreciated. I haven't yet updated my catalogues this weekend so I'll pull these changes in tomorrow.
